//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WendtEquipmentTracking.DataAccess.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillOfLanding
    {
        public int BillOfLandingId { get; set; }
        public int EquipmentId { get; set; }
        public int Revision { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string BillOfLandingNumber { get; set; }
        public Nullable<System.DateTime> DateShipped { get; set; }
        public string ShippedFrom { get; set; }
        public string ShipToCompany { get; set; }
        public string ShipToAddress { get; set; }
        public string ShipToCSZ { get; set; }
        public string ShipToPhoneFax { get; set; }
        public string ShipToContact1 { get; set; }
        public string ShipToContact2 { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
