//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WendtEquipmentTracking.DataAccess.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillOfLandingEquipment
    {
        public int BillOfLandingEquipmentId { get; set; }
        public int BillOfLandingId { get; set; }
        public int EquipmentId { get; set; }
        public double Quantity { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual BillOfLanding BillOfLanding { get; set; }
    }
}
