//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WendtEquipmentTracking.DataAccess.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckingSchedule
    {
        public int TruckingScheduleId { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string PurchaseOrder { get; set; }
        public string RequestedBy { get; set; }
        public Nullable<int> ShipFromVendorId { get; set; }
        public Nullable<int> ShipToVendorId { get; set; }
        public string Description { get; set; }
        public Nullable<double> NumPieces { get; set; }
        public string Dimensions { get; set; }
        public Nullable<double> Weight { get; set; }
        public string Carrier { get; set; }
        public Nullable<System.DateTime> PickUpDate { get; set; }
        public string Comments { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual Vendor Vendor1 { get; set; }
    }
}
