//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Infrastructure.MappingViews;

[assembly: DbMappingViewCacheTypeAttribute(
    typeof(WendtEquipmentTracking.DataAccess.SQL.WendtEquipmentTrackingEntities),
    typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets31a96fc05a98687d3bb36db0bf1b8d679b75d6a595b0dce33e53b736174bd6b0))]

namespace Edm_EntityMappingGeneratedViews
{
    using System;
    using System.CodeDom.Compiler;
    using System.Data.Entity.Core.Metadata.Edm;

    /// <summary>
    /// Implements a mapping view cache.
    /// </summary>
    [GeneratedCode("Entity Framework 6 Power Tools", "0.9.2.0")]
    internal sealed class ViewsForBaseEntitySets31a96fc05a98687d3bb36db0bf1b8d679b75d6a595b0dce33e53b736174bd6b0 : DbMappingViewCache
    {
        /// <summary>
        /// Gets a hash value computed over the mapping closure.
        /// </summary>
        public override string MappingHashValue
        {
            get { return "31a96fc05a98687d3bb36db0bf1b8d679b75d6a595b0dce33e53b736174bd6b0"; }
        }

        /// <summary>
        /// Gets a view corresponding to the specified extent.
        /// </summary>
        /// <param name="extent">The extent.</param>
        /// <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>
        public override DbMappingView GetView(EntitySetBase extent)
        {
            if (extent == null)
            {
                throw new ArgumentNullException("extent");
            }

            var extentName = extent.EntityContainer.Name + "." + extent.Name;

            if (extentName == "WendtEquipmentTrackingDataAccessSQLModelStoreContainer.BillOfLading")
            {
                return GetView0();
            }

            if (extentName == "WendtEquipmentTrackingDataAccessSQLModelStoreContainer.BillOfLadingAttachment")
            {
                return GetView1();
            }

            if (extentName == "WendtEquipmentTrackingDataAccessSQLModelStoreContainer.BillOfLadingEquipment")
            {
                return GetView2();
            }

            if (extentName == "WendtEquipmentTrackingDataAccessSQLModelStoreContainer.Equipment")
            {
                return GetView3();
            }

            if (extentName == "WendtEquipmentTrackingDataAccessSQLModelStoreContainer.EquipmentAttachment")
            {
                return GetView4();
            }

            if (extentName == "WendtEquipmentTrackingDataAccessSQLModelStoreContainer.HardwareKit")
            {
                return GetView5();
            }

            if (extentName == "WendtEquipmentTrackingDataAccessSQLModelStoreContainer.HardwareKitEquipment")
            {
                return GetView6();
            }

            if (extentName == "WendtEquipmentTrackingDataAccessSQLModelStoreContainer.Priority")
            {
                return GetView7();
            }

            if (extentName == "WendtEquipmentTrackingDataAccessSQLModelStoreContainer.Project")
            {
                return GetView8();
            }

            if (extentName == "WendtEquipmentTrackingDataAccessSQLModelStoreContainer.TruckingSchedule")
            {
                return GetView9();
            }

            if (extentName == "WendtEquipmentTrackingDataAccessSQLModelStoreContainer.Vendor")
            {
                return GetView10();
            }

            if (extentName == "WendtEquipmentTrackingDataAccessSQLModelStoreContainer.WorkOrderPrice")
            {
                return GetView11();
            }

            if (extentName == "WendtEquipmentTrackingEntities.BillOfLadings")
            {
                return GetView12();
            }

            if (extentName == "WendtEquipmentTrackingEntities.BillOfLadingAttachments")
            {
                return GetView13();
            }

            if (extentName == "WendtEquipmentTrackingEntities.BillOfLadingEquipments")
            {
                return GetView14();
            }

            if (extentName == "WendtEquipmentTrackingEntities.Equipments")
            {
                return GetView15();
            }

            if (extentName == "WendtEquipmentTrackingEntities.EquipmentAttachments")
            {
                return GetView16();
            }

            if (extentName == "WendtEquipmentTrackingEntities.HardwareKits")
            {
                return GetView17();
            }

            if (extentName == "WendtEquipmentTrackingEntities.HardwareKitEquipments")
            {
                return GetView18();
            }

            if (extentName == "WendtEquipmentTrackingEntities.Priorities")
            {
                return GetView19();
            }

            if (extentName == "WendtEquipmentTrackingEntities.Projects")
            {
                return GetView20();
            }

            if (extentName == "WendtEquipmentTrackingEntities.TruckingSchedules")
            {
                return GetView21();
            }

            if (extentName == "WendtEquipmentTrackingEntities.Vendors")
            {
                return GetView22();
            }

            if (extentName == "WendtEquipmentTrackingEntities.WorkOrderPrices")
            {
                return GetView23();
            }

            if (extentName == "WendtEquipmentTrackingDataAccessSQLModelStoreContainer.Broker")
            {
                return GetView24();
            }

            if (extentName == "WendtEquipmentTrackingEntities.Brokers")
            {
                return GetView25();
            }

            if (extentName == "WendtEquipmentTrackingDataAccessSQLModelStoreContainer.HardwareCommercialCode")
            {
                return GetView26();
            }

            if (extentName == "WendtEquipmentTrackingEntities.HardwareCommercialCodes")
            {
                return GetView27();
            }

            if (extentName == "WendtEquipmentTrackingDataAccessSQLModelStoreContainer.User")
            {
                return GetView28();
            }

            if (extentName == "WendtEquipmentTrackingEntities.Users")
            {
                return GetView29();
            }

            return null;
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingDataAccessSQLModelStoreContainer.BillOfLading.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView0()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing BillOfLading
        [WendtEquipmentTracking.DataAccess.SQL.Model.Store.BillOfLading](T1.BillOfLading_BillOfLadingId, T1.BillOfLading_ProjectId, T1.BillOfLading_Revision, T1.BillOfLading_IsCurrentRevision, T1.BillOfLading_CreatedBy, T1.BillOfLading_CreatedDate, T1.BillOfLading_ModifiedBy, T1.BillOfLading_ModifiedDate, T1.BillOfLading_BillOfLadingNumber, T1.BillOfLading_DateShipped, T1.BillOfLading_ToStorage, T1.BillOfLading_TrailerNumber, T1.BillOfLading_Carrier, T1.BillOfLading_FreightTerms, T1.BillOfLading_ShippedFrom, T1.BillOfLading_ShippedTo, T1.BillOfLading_IsLocked, T1.BillOfLading_LockedDate, T1.BillOfLading_LockedBy, T1.BillOfLading_IsDeleted)
    FROM (
        SELECT 
            T.BillOfLadingId AS BillOfLading_BillOfLadingId, 
            T.ProjectId AS BillOfLading_ProjectId, 
            T.Revision AS BillOfLading_Revision, 
            T.IsCurrentRevision AS BillOfLading_IsCurrentRevision, 
            T.CreatedBy AS BillOfLading_CreatedBy, 
            T.CreatedDate AS BillOfLading_CreatedDate, 
            T.ModifiedBy AS BillOfLading_ModifiedBy, 
            T.ModifiedDate AS BillOfLading_ModifiedDate, 
            T.BillOfLadingNumber AS BillOfLading_BillOfLadingNumber, 
            T.DateShipped AS BillOfLading_DateShipped, 
            T.ToStorage AS BillOfLading_ToStorage, 
            T.TrailerNumber AS BillOfLading_TrailerNumber, 
            T.Carrier AS BillOfLading_Carrier, 
            T.FreightTerms AS BillOfLading_FreightTerms, 
            T.ShippedFrom AS BillOfLading_ShippedFrom, 
            T.ShippedTo AS BillOfLading_ShippedTo, 
            T.IsLocked AS BillOfLading_IsLocked, 
            T.LockedDate AS BillOfLading_LockedDate, 
            T.LockedBy AS BillOfLading_LockedBy, 
            T.IsDeleted AS BillOfLading_IsDeleted, 
            True AS _from0
        FROM WendtEquipmentTrackingEntities.BillOfLadings AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingDataAccessSQLModelStoreContainer.BillOfLadingAttachment.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView1()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing BillOfLadingAttachment
        [WendtEquipmentTracking.DataAccess.SQL.Model.Store.BillOfLadingAttachment](T1.BillOfLadingAttachment_BillOfLadingAttachmentId, T1.BillOfLadingAttachment_BillOfLadingId, T1.BillOfLadingAttachment_FileName, T1.BillOfLadingAttachment_FileTitle, T1.BillOfLadingAttachment_IsDeleted, T1.BillOfLadingAttachment_CreatedBy, T1.BillOfLadingAttachment_CreatedDate, T1.BillOfLadingAttachment_ModifiedBy, T1.BillOfLadingAttachment_ModifiedDate)
    FROM (
        SELECT 
            T.BillOfLadingAttachmentId AS BillOfLadingAttachment_BillOfLadingAttachmentId, 
            T.BillOfLadingId AS BillOfLadingAttachment_BillOfLadingId, 
            T.FileName AS BillOfLadingAttachment_FileName, 
            T.FileTitle AS BillOfLadingAttachment_FileTitle, 
            T.IsDeleted AS BillOfLadingAttachment_IsDeleted, 
            T.CreatedBy AS BillOfLadingAttachment_CreatedBy, 
            T.CreatedDate AS BillOfLadingAttachment_CreatedDate, 
            T.ModifiedBy AS BillOfLadingAttachment_ModifiedBy, 
            T.ModifiedDate AS BillOfLadingAttachment_ModifiedDate, 
            True AS _from0
        FROM WendtEquipmentTrackingEntities.BillOfLadingAttachments AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingDataAccessSQLModelStoreContainer.BillOfLadingEquipment.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView2()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing BillOfLadingEquipment
        [WendtEquipmentTracking.DataAccess.SQL.Model.Store.BillOfLadingEquipment](T1.BillOfLadingEquipment_BillOfLadingEquipmentId, T1.BillOfLadingEquipment_BillOfLadingId, T1.BillOfLadingEquipment_EquipmentId, T1.BillOfLadingEquipment_Quantity, T1.BillOfLadingEquipment_ShippedFrom, T1.BillOfLadingEquipment_IsDeleted)
    FROM (
        SELECT 
            T.BillOfLadingEquipmentId AS BillOfLadingEquipment_BillOfLadingEquipmentId, 
            T.BillOfLadingId AS BillOfLadingEquipment_BillOfLadingId, 
            T.EquipmentId AS BillOfLadingEquipment_EquipmentId, 
            T.Quantity AS BillOfLadingEquipment_Quantity, 
            T.ShippedFrom AS BillOfLadingEquipment_ShippedFrom, 
            T.IsDeleted AS BillOfLadingEquipment_IsDeleted, 
            True AS _from0
        FROM WendtEquipmentTrackingEntities.BillOfLadingEquipments AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingDataAccessSQLModelStoreContainer.Equipment.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView3()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Equipment
        [WendtEquipmentTracking.DataAccess.SQL.Model.Store.Equipment](T1.Equipment_EquipmentId, T1.Equipment_ProjectId, T1.Equipment_EquipmentName, T1.Equipment_PriorityId, T1.Equipment_CreatedBy, T1.Equipment_CreatedDate, T1.Equipment_ModifiedBy, T1.Equipment_ModifiedDate, T1.Equipment_ReleaseDate, T1.Equipment_DrawingNumber, T1.Equipment_WorkOrderNumber, T1.Equipment_Quantity, T1.Equipment_ShippingTagNumber, T1.Equipment_Description, T1.Equipment_UnitWeight, T1.Equipment_TotalWeight, T1.Equipment_TotalWeightShipped, T1.Equipment_ReadyToShip, T1.Equipment_ShippedQuantity, T1.Equipment_LeftToShip, T1.Equipment_FullyShipped, T1.Equipment_CustomsValue, T1.Equipment_SalePrice, T1.Equipment_Notes, T1.Equipment_ShippedFrom, T1.Equipment_HTSCode, T1.Equipment_CountryOfOrigin, T1.Equipment_IsHardware, T1.Equipment_IsDeleted, T1.Equipment_HardwareKitId)
    FROM (
        SELECT 
            T.EquipmentId AS Equipment_EquipmentId, 
            T.ProjectId AS Equipment_ProjectId, 
            T.EquipmentName AS Equipment_EquipmentName, 
            T.PriorityId AS Equipment_PriorityId, 
            T.CreatedBy AS Equipment_CreatedBy, 
            T.CreatedDate AS Equipment_CreatedDate, 
            T.ModifiedBy AS Equipment_ModifiedBy, 
            T.ModifiedDate AS Equipment_ModifiedDate, 
            T.ReleaseDate AS Equipment_ReleaseDate, 
            T.DrawingNumber AS Equipment_DrawingNumber, 
            T.WorkOrderNumber AS Equipment_WorkOrderNumber, 
            T.Quantity AS Equipment_Quantity, 
            T.ShippingTagNumber AS Equipment_ShippingTagNumber, 
            T.Description AS Equipment_Description, 
            T.UnitWeight AS Equipment_UnitWeight, 
            T.TotalWeight AS Equipment_TotalWeight, 
            T.TotalWeightShipped AS Equipment_TotalWeightShipped, 
            T.ReadyToShip AS Equipment_ReadyToShip, 
            T.ShippedQuantity AS Equipment_ShippedQuantity, 
            T.LeftToShip AS Equipment_LeftToShip, 
            T.FullyShipped AS Equipment_FullyShipped, 
            T.CustomsValue AS Equipment_CustomsValue, 
            T.SalePrice AS Equipment_SalePrice, 
            T.Notes AS Equipment_Notes, 
            T.ShippedFrom AS Equipment_ShippedFrom, 
            T.HTSCode AS Equipment_HTSCode, 
            T.CountryOfOrigin AS Equipment_CountryOfOrigin, 
            T.IsHardware AS Equipment_IsHardware, 
            T.IsDeleted AS Equipment_IsDeleted, 
            T.HardwareKitId AS Equipment_HardwareKitId, 
            True AS _from0
        FROM WendtEquipmentTrackingEntities.Equipments AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingDataAccessSQLModelStoreContainer.EquipmentAttachment.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView4()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing EquipmentAttachment
        [WendtEquipmentTracking.DataAccess.SQL.Model.Store.EquipmentAttachment](T1.EquipmentAttachment_EquipmentAttachmentId, T1.EquipmentAttachment_EquipmentId, T1.EquipmentAttachment_FileName, T1.EquipmentAttachment_FileTitle, T1.EquipmentAttachment_IsDeleted, T1.EquipmentAttachment_CreatedBy, T1.EquipmentAttachment_CreatedDate, T1.EquipmentAttachment_ModifiedBy, T1.EquipmentAttachment_ModifiedDate)
    FROM (
        SELECT 
            T.EquipmentAttachmentId AS EquipmentAttachment_EquipmentAttachmentId, 
            T.EquipmentId AS EquipmentAttachment_EquipmentId, 
            T.FileName AS EquipmentAttachment_FileName, 
            T.FileTitle AS EquipmentAttachment_FileTitle, 
            T.IsDeleted AS EquipmentAttachment_IsDeleted, 
            T.CreatedBy AS EquipmentAttachment_CreatedBy, 
            T.CreatedDate AS EquipmentAttachment_CreatedDate, 
            T.ModifiedBy AS EquipmentAttachment_ModifiedBy, 
            T.ModifiedDate AS EquipmentAttachment_ModifiedDate, 
            True AS _from0
        FROM WendtEquipmentTrackingEntities.EquipmentAttachments AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingDataAccessSQLModelStoreContainer.HardwareKit.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView5()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing HardwareKit
        [WendtEquipmentTracking.DataAccess.SQL.Model.Store.HardwareKit](T1.HardwareKit_HardwareKitId, T1.HardwareKit_ProjectId, T1.HardwareKit_Revision, T1.HardwareKit_IsCurrentRevision, T1.HardwareKit_HardwareKitNumber, T1.HardwareKit_ExtraQuantityPercentage, T1.HardwareKit_CreatedBy, T1.HardwareKit_CreatedDate, T1.HardwareKit_ModifiedBy, T1.HardwareKit_ModifiedDate, T1.HardwareKit_IsDeleted)
    FROM (
        SELECT 
            T.HardwareKitId AS HardwareKit_HardwareKitId, 
            T.ProjectId AS HardwareKit_ProjectId, 
            T.Revision AS HardwareKit_Revision, 
            T.IsCurrentRevision AS HardwareKit_IsCurrentRevision, 
            T.HardwareKitNumber AS HardwareKit_HardwareKitNumber, 
            T.ExtraQuantityPercentage AS HardwareKit_ExtraQuantityPercentage, 
            T.CreatedBy AS HardwareKit_CreatedBy, 
            T.CreatedDate AS HardwareKit_CreatedDate, 
            T.ModifiedBy AS HardwareKit_ModifiedBy, 
            T.ModifiedDate AS HardwareKit_ModifiedDate, 
            T.IsDeleted AS HardwareKit_IsDeleted, 
            True AS _from0
        FROM WendtEquipmentTrackingEntities.HardwareKits AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingDataAccessSQLModelStoreContainer.HardwareKitEquipment.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView6()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing HardwareKitEquipment
        [WendtEquipmentTracking.DataAccess.SQL.Model.Store.HardwareKitEquipment](T1.HardwareKitEquipment_HardwareKitEquipmentId, T1.HardwareKitEquipment_HardwareKitId, T1.HardwareKitEquipment_EquipmentId, T1.HardwareKitEquipment_QuantityToShip, T1.HardwareKitEquipment_IsDeleted)
    FROM (
        SELECT 
            T.HardwareKitEquipmentId AS HardwareKitEquipment_HardwareKitEquipmentId, 
            T.HardwareKitId AS HardwareKitEquipment_HardwareKitId, 
            T.EquipmentId AS HardwareKitEquipment_EquipmentId, 
            T.QuantityToShip AS HardwareKitEquipment_QuantityToShip, 
            T.IsDeleted AS HardwareKitEquipment_IsDeleted, 
            True AS _from0
        FROM WendtEquipmentTrackingEntities.HardwareKitEquipments AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingDataAccessSQLModelStoreContainer.Priority.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView7()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Priority
        [WendtEquipmentTracking.DataAccess.SQL.Model.Store.Priority](T1.Priority_PriorityId, T1.Priority_ProjectId, T1.Priority_PriorityNumber, T1.Priority_DueDate, T1.Priority_EndDate, T1.Priority_ContractualShipDate, T1.Priority_EquipmentName, T1.Priority_CreatedBy, T1.Priority_CreatedDate, T1.Priority_ModifiedBy, T1.Priority_ModifiedDate, T1.Priority_IsDeleted)
    FROM (
        SELECT 
            T.PriorityId AS Priority_PriorityId, 
            T.ProjectId AS Priority_ProjectId, 
            T.PriorityNumber AS Priority_PriorityNumber, 
            T.DueDate AS Priority_DueDate, 
            T.EndDate AS Priority_EndDate, 
            T.ContractualShipDate AS Priority_ContractualShipDate, 
            T.EquipmentName AS Priority_EquipmentName, 
            T.CreatedBy AS Priority_CreatedBy, 
            T.CreatedDate AS Priority_CreatedDate, 
            T.ModifiedBy AS Priority_ModifiedBy, 
            T.ModifiedDate AS Priority_ModifiedDate, 
            T.IsDeleted AS Priority_IsDeleted, 
            True AS _from0
        FROM WendtEquipmentTrackingEntities.Priorities AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingDataAccessSQLModelStoreContainer.Project.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView8()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Project
        [WendtEquipmentTracking.DataAccess.SQL.Model.Store.Project](T1.Project_ProjectId, T1.Project_ProjectNumber, T1.Project_CreatedBy, T1.Project_CreatedDate, T1.Project_ModifiedBy, T1.Project_ModifiedDate, T1.Project_FreightTerms, T1.Project_ShipToCompany, T1.Project_ShipToAddress, T1.Project_ShipToCSZ, T1.Project_ShipToContact1, T1.Project_ShipToContact1PhoneFax, T1.Project_ShipToContact1Email, T1.Project_ShipToContact2, T1.Project_ShipToContact2PhoneFax, T1.Project_ShipToContact2Email, T1.Project_ShipToBroker, T1.Project_ShipToBrokerPhoneFax, T1.Project_ShipToBrokerEmail, T1.Project_PM, T1.Project_ReceivingHours, T1.Project_Notes, T1.Project_IsCustomsProject, T1.Project_IncludeSoftCosts, T1.Project_IsCompleted, T1.Project_IsDeleted)
    FROM (
        SELECT 
            T.ProjectId AS Project_ProjectId, 
            T.ProjectNumber AS Project_ProjectNumber, 
            T.CreatedBy AS Project_CreatedBy, 
            T.CreatedDate AS Project_CreatedDate, 
            T.ModifiedBy AS Project_ModifiedBy, 
            T.ModifiedDate AS Project_ModifiedDate, 
            T.FreightTerms AS Project_FreightTerms, 
            T.ShipToCompany AS Project_ShipToCompany, 
            T.ShipToAddress AS Project_ShipToAddress, 
            T.ShipToCSZ AS Project_ShipToCSZ, 
            T.ShipToContact1 AS Project_ShipToContact1, 
            T.ShipToContact1PhoneFax AS Project_ShipToContact1PhoneFax, 
            T.ShipToContact1Email AS Project_ShipToContact1Email, 
            T.ShipToContact2 AS Project_ShipToContact2, 
            T.ShipToContact2PhoneFax AS Project_ShipToContact2PhoneFax, 
            T.ShipToContact2Email AS Project_ShipToContact2Email, 
            T.ShipToBroker AS Project_ShipToBroker, 
            T.ShipToBrokerPhoneFax AS Project_ShipToBrokerPhoneFax, 
            T.ShipToBrokerEmail AS Project_ShipToBrokerEmail, 
            T.PM AS Project_PM, 
            T.ReceivingHours AS Project_ReceivingHours, 
            T.Notes AS Project_Notes, 
            T.IsCustomsProject AS Project_IsCustomsProject, 
            T.IncludeSoftCosts AS Project_IncludeSoftCosts, 
            T.IsCompleted AS Project_IsCompleted, 
            T.IsDeleted AS Project_IsDeleted, 
            True AS _from0
        FROM WendtEquipmentTrackingEntities.Projects AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingDataAccessSQLModelStoreContainer.TruckingSchedule.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView9()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing TruckingSchedule
        [WendtEquipmentTracking.DataAccess.SQL.Model.Store.TruckingSchedule](T1.TruckingSchedule_TruckingScheduleId, T1.TruckingSchedule_RequestDate, T1.TruckingSchedule_ProjectId, T1.TruckingSchedule_WorkOrder, T1.TruckingSchedule_PurchaseOrder, T1.TruckingSchedule_RequestedBy, T1.TruckingSchedule_ShipFromVendorId, T1.TruckingSchedule_ShipToVendorId, T1.TruckingSchedule_Description, T1.TruckingSchedule_NumPieces, T1.TruckingSchedule_Dimensions, T1.TruckingSchedule_Weight, T1.TruckingSchedule_Carrier, T1.TruckingSchedule_PickUpDate, T1.TruckingSchedule_Comments, T1.TruckingSchedule_Status, T1.TruckingSchedule_CreatedBy, T1.TruckingSchedule_CreatedDate, T1.TruckingSchedule_ModifiedBy, T1.TruckingSchedule_ModifiedDate, T1.TruckingSchedule_IsDeleted)
    FROM (
        SELECT 
            T.TruckingScheduleId AS TruckingSchedule_TruckingScheduleId, 
            T.RequestDate AS TruckingSchedule_RequestDate, 
            T.ProjectId AS TruckingSchedule_ProjectId, 
            T.WorkOrder AS TruckingSchedule_WorkOrder, 
            T.PurchaseOrder AS TruckingSchedule_PurchaseOrder, 
            T.RequestedBy AS TruckingSchedule_RequestedBy, 
            T.ShipFromVendorId AS TruckingSchedule_ShipFromVendorId, 
            T.ShipToVendorId AS TruckingSchedule_ShipToVendorId, 
            T.Description AS TruckingSchedule_Description, 
            T.NumPieces AS TruckingSchedule_NumPieces, 
            T.Dimensions AS TruckingSchedule_Dimensions, 
            T.Weight AS TruckingSchedule_Weight, 
            T.Carrier AS TruckingSchedule_Carrier, 
            T.PickUpDate AS TruckingSchedule_PickUpDate, 
            T.Comments AS TruckingSchedule_Comments, 
            T.Status AS TruckingSchedule_Status, 
            T.CreatedBy AS TruckingSchedule_CreatedBy, 
            T.CreatedDate AS TruckingSchedule_CreatedDate, 
            T.ModifiedBy AS TruckingSchedule_ModifiedBy, 
            T.ModifiedDate AS TruckingSchedule_ModifiedDate, 
            T.IsDeleted AS TruckingSchedule_IsDeleted, 
            True AS _from0
        FROM WendtEquipmentTrackingEntities.TruckingSchedules AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingDataAccessSQLModelStoreContainer.Vendor.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView10()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Vendor
        [WendtEquipmentTracking.DataAccess.SQL.Model.Store.Vendor](T1.Vendor_VendorId, T1.Vendor_Name, T1.Vendor_Address, T1.Vendor_Contact1, T1.Vendor_PhoneFax, T1.Vendor_Email, T1.Vendor_CreatedBy, T1.Vendor_CreatedDate, T1.Vendor_ModifiedBy, T1.Vendor_ModifiedDate, T1.Vendor_IsDeleted)
    FROM (
        SELECT 
            T.VendorId AS Vendor_VendorId, 
            T.Name AS Vendor_Name, 
            T.Address AS Vendor_Address, 
            T.Contact1 AS Vendor_Contact1, 
            T.PhoneFax AS Vendor_PhoneFax, 
            T.Email AS Vendor_Email, 
            T.CreatedBy AS Vendor_CreatedBy, 
            T.CreatedDate AS Vendor_CreatedDate, 
            T.ModifiedBy AS Vendor_ModifiedBy, 
            T.ModifiedDate AS Vendor_ModifiedDate, 
            T.IsDeleted AS Vendor_IsDeleted, 
            True AS _from0
        FROM WendtEquipmentTrackingEntities.Vendors AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingDataAccessSQLModelStoreContainer.WorkOrderPrice.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView11()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing WorkOrderPrice
        [WendtEquipmentTracking.DataAccess.SQL.Model.Store.WorkOrderPrice](T1.WorkOrderPrice_WorkOrderPriceId, T1.WorkOrderPrice_ProjectId, T1.WorkOrderPrice_WorkOrderNumber, T1.WorkOrderPrice_SalePrice, T1.WorkOrderPrice_CostPrice, T1.WorkOrderPrice_TotalWeight, T1.WorkOrderPrice_ReleasedPercent, T1.WorkOrderPrice_ShippedPercent, T1.WorkOrderPrice_CreatedBy, T1.WorkOrderPrice_CreatedDate, T1.WorkOrderPrice_ModifiedBy, T1.WorkOrderPrice_ModifiedDate, T1.WorkOrderPrice_IsDeleted)
    FROM (
        SELECT 
            T.WorkOrderPriceId AS WorkOrderPrice_WorkOrderPriceId, 
            T.ProjectId AS WorkOrderPrice_ProjectId, 
            T.WorkOrderNumber AS WorkOrderPrice_WorkOrderNumber, 
            T.SalePrice AS WorkOrderPrice_SalePrice, 
            T.CostPrice AS WorkOrderPrice_CostPrice, 
            T.TotalWeight AS WorkOrderPrice_TotalWeight, 
            T.ReleasedPercent AS WorkOrderPrice_ReleasedPercent, 
            T.ShippedPercent AS WorkOrderPrice_ShippedPercent, 
            T.CreatedBy AS WorkOrderPrice_CreatedBy, 
            T.CreatedDate AS WorkOrderPrice_CreatedDate, 
            T.ModifiedBy AS WorkOrderPrice_ModifiedBy, 
            T.ModifiedDate AS WorkOrderPrice_ModifiedDate, 
            T.IsDeleted AS WorkOrderPrice_IsDeleted, 
            True AS _from0
        FROM WendtEquipmentTrackingEntities.WorkOrderPrices AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingEntities.BillOfLadings.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView12()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing BillOfLadings
        [WendtEquipmentTracking.DataAccess.SQL.Model.BillOfLading](T1.BillOfLading_BillOfLadingId, T1.BillOfLading_ProjectId, T1.BillOfLading_Revision, T1.BillOfLading_IsCurrentRevision, T1.BillOfLading_CreatedBy, T1.BillOfLading_CreatedDate, T1.BillOfLading_ModifiedBy, T1.BillOfLading_ModifiedDate, T1.BillOfLading_BillOfLadingNumber, T1.BillOfLading_DateShipped, T1.BillOfLading_ToStorage, T1.BillOfLading_TrailerNumber, T1.BillOfLading_Carrier, T1.BillOfLading_FreightTerms, T1.BillOfLading_ShippedFrom, T1.BillOfLading_ShippedTo, T1.BillOfLading_IsLocked, T1.BillOfLading_LockedDate, T1.BillOfLading_LockedBy, T1.BillOfLading_IsDeleted)
    FROM (
        SELECT 
            T.BillOfLadingId AS BillOfLading_BillOfLadingId, 
            T.ProjectId AS BillOfLading_ProjectId, 
            T.Revision AS BillOfLading_Revision, 
            T.IsCurrentRevision AS BillOfLading_IsCurrentRevision, 
            T.CreatedBy AS BillOfLading_CreatedBy, 
            T.CreatedDate AS BillOfLading_CreatedDate, 
            T.ModifiedBy AS BillOfLading_ModifiedBy, 
            T.ModifiedDate AS BillOfLading_ModifiedDate, 
            T.BillOfLadingNumber AS BillOfLading_BillOfLadingNumber, 
            T.DateShipped AS BillOfLading_DateShipped, 
            T.ToStorage AS BillOfLading_ToStorage, 
            T.TrailerNumber AS BillOfLading_TrailerNumber, 
            T.Carrier AS BillOfLading_Carrier, 
            T.FreightTerms AS BillOfLading_FreightTerms, 
            T.ShippedFrom AS BillOfLading_ShippedFrom, 
            T.ShippedTo AS BillOfLading_ShippedTo, 
            T.IsLocked AS BillOfLading_IsLocked, 
            T.LockedDate AS BillOfLading_LockedDate, 
            T.LockedBy AS BillOfLading_LockedBy, 
            T.IsDeleted AS BillOfLading_IsDeleted, 
            True AS _from0
        FROM WendtEquipmentTrackingDataAccessSQLModelStoreContainer.BillOfLading AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingEntities.BillOfLadingAttachments.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView13()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing BillOfLadingAttachments
        [WendtEquipmentTracking.DataAccess.SQL.Model.BillOfLadingAttachment](T1.BillOfLadingAttachment_BillOfLadingAttachmentId, T1.BillOfLadingAttachment_BillOfLadingId, T1.BillOfLadingAttachment_FileName, T1.BillOfLadingAttachment_FileTitle, T1.BillOfLadingAttachment_IsDeleted, T1.BillOfLadingAttachment_CreatedBy, T1.BillOfLadingAttachment_CreatedDate, T1.BillOfLadingAttachment_ModifiedBy, T1.BillOfLadingAttachment_ModifiedDate)
    FROM (
        SELECT 
            T.BillOfLadingAttachmentId AS BillOfLadingAttachment_BillOfLadingAttachmentId, 
            T.BillOfLadingId AS BillOfLadingAttachment_BillOfLadingId, 
            T.FileName AS BillOfLadingAttachment_FileName, 
            T.FileTitle AS BillOfLadingAttachment_FileTitle, 
            T.IsDeleted AS BillOfLadingAttachment_IsDeleted, 
            T.CreatedBy AS BillOfLadingAttachment_CreatedBy, 
            T.CreatedDate AS BillOfLadingAttachment_CreatedDate, 
            T.ModifiedBy AS BillOfLadingAttachment_ModifiedBy, 
            T.ModifiedDate AS BillOfLadingAttachment_ModifiedDate, 
            True AS _from0
        FROM WendtEquipmentTrackingDataAccessSQLModelStoreContainer.BillOfLadingAttachment AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingEntities.BillOfLadingEquipments.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView14()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing BillOfLadingEquipments
        [WendtEquipmentTracking.DataAccess.SQL.Model.BillOfLadingEquipment](T1.BillOfLadingEquipment_BillOfLadingEquipmentId, T1.BillOfLadingEquipment_BillOfLadingId, T1.BillOfLadingEquipment_EquipmentId, T1.BillOfLadingEquipment_Quantity, T1.BillOfLadingEquipment_ShippedFrom, T1.BillOfLadingEquipment_IsDeleted)
    FROM (
        SELECT 
            T.BillOfLadingEquipmentId AS BillOfLadingEquipment_BillOfLadingEquipmentId, 
            T.BillOfLadingId AS BillOfLadingEquipment_BillOfLadingId, 
            T.EquipmentId AS BillOfLadingEquipment_EquipmentId, 
            T.Quantity AS BillOfLadingEquipment_Quantity, 
            T.ShippedFrom AS BillOfLadingEquipment_ShippedFrom, 
            T.IsDeleted AS BillOfLadingEquipment_IsDeleted, 
            True AS _from0
        FROM WendtEquipmentTrackingDataAccessSQLModelStoreContainer.BillOfLadingEquipment AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingEntities.Equipments.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView15()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Equipments
        [WendtEquipmentTracking.DataAccess.SQL.Model.Equipment](T1.Equipment_EquipmentId, T1.Equipment_ProjectId, T1.Equipment_EquipmentName, T1.Equipment_PriorityId, T1.Equipment_CreatedBy, T1.Equipment_CreatedDate, T1.Equipment_ModifiedBy, T1.Equipment_ModifiedDate, T1.Equipment_ReleaseDate, T1.Equipment_DrawingNumber, T1.Equipment_WorkOrderNumber, T1.Equipment_Quantity, T1.Equipment_ShippingTagNumber, T1.Equipment_Description, T1.Equipment_UnitWeight, T1.Equipment_TotalWeight, T1.Equipment_TotalWeightShipped, T1.Equipment_ReadyToShip, T1.Equipment_ShippedQuantity, T1.Equipment_LeftToShip, T1.Equipment_FullyShipped, T1.Equipment_CustomsValue, T1.Equipment_SalePrice, T1.Equipment_Notes, T1.Equipment_ShippedFrom, T1.Equipment_HTSCode, T1.Equipment_CountryOfOrigin, T1.Equipment_IsHardware, T1.Equipment_IsDeleted, T1.Equipment_HardwareKitId)
    FROM (
        SELECT 
            T.EquipmentId AS Equipment_EquipmentId, 
            T.ProjectId AS Equipment_ProjectId, 
            T.EquipmentName AS Equipment_EquipmentName, 
            T.PriorityId AS Equipment_PriorityId, 
            T.CreatedBy AS Equipment_CreatedBy, 
            T.CreatedDate AS Equipment_CreatedDate, 
            T.ModifiedBy AS Equipment_ModifiedBy, 
            T.ModifiedDate AS Equipment_ModifiedDate, 
            T.ReleaseDate AS Equipment_ReleaseDate, 
            T.DrawingNumber AS Equipment_DrawingNumber, 
            T.WorkOrderNumber AS Equipment_WorkOrderNumber, 
            T.Quantity AS Equipment_Quantity, 
            T.ShippingTagNumber AS Equipment_ShippingTagNumber, 
            T.Description AS Equipment_Description, 
            T.UnitWeight AS Equipment_UnitWeight, 
            T.TotalWeight AS Equipment_TotalWeight, 
            T.TotalWeightShipped AS Equipment_TotalWeightShipped, 
            T.ReadyToShip AS Equipment_ReadyToShip, 
            T.ShippedQuantity AS Equipment_ShippedQuantity, 
            T.LeftToShip AS Equipment_LeftToShip, 
            T.FullyShipped AS Equipment_FullyShipped, 
            T.CustomsValue AS Equipment_CustomsValue, 
            T.SalePrice AS Equipment_SalePrice, 
            T.Notes AS Equipment_Notes, 
            T.ShippedFrom AS Equipment_ShippedFrom, 
            T.HTSCode AS Equipment_HTSCode, 
            T.CountryOfOrigin AS Equipment_CountryOfOrigin, 
            T.IsHardware AS Equipment_IsHardware, 
            T.IsDeleted AS Equipment_IsDeleted, 
            T.HardwareKitId AS Equipment_HardwareKitId, 
            True AS _from0
        FROM WendtEquipmentTrackingDataAccessSQLModelStoreContainer.Equipment AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingEntities.EquipmentAttachments.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView16()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing EquipmentAttachments
        [WendtEquipmentTracking.DataAccess.SQL.Model.EquipmentAttachment](T1.EquipmentAttachment_EquipmentAttachmentId, T1.EquipmentAttachment_EquipmentId, T1.EquipmentAttachment_FileName, T1.EquipmentAttachment_FileTitle, T1.EquipmentAttachment_IsDeleted, T1.EquipmentAttachment_CreatedBy, T1.EquipmentAttachment_CreatedDate, T1.EquipmentAttachment_ModifiedBy, T1.EquipmentAttachment_ModifiedDate)
    FROM (
        SELECT 
            T.EquipmentAttachmentId AS EquipmentAttachment_EquipmentAttachmentId, 
            T.EquipmentId AS EquipmentAttachment_EquipmentId, 
            T.FileName AS EquipmentAttachment_FileName, 
            T.FileTitle AS EquipmentAttachment_FileTitle, 
            T.IsDeleted AS EquipmentAttachment_IsDeleted, 
            T.CreatedBy AS EquipmentAttachment_CreatedBy, 
            T.CreatedDate AS EquipmentAttachment_CreatedDate, 
            T.ModifiedBy AS EquipmentAttachment_ModifiedBy, 
            T.ModifiedDate AS EquipmentAttachment_ModifiedDate, 
            True AS _from0
        FROM WendtEquipmentTrackingDataAccessSQLModelStoreContainer.EquipmentAttachment AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingEntities.HardwareKits.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView17()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing HardwareKits
        [WendtEquipmentTracking.DataAccess.SQL.Model.HardwareKit](T1.HardwareKit_HardwareKitId, T1.HardwareKit_ProjectId, T1.HardwareKit_Revision, T1.HardwareKit_IsCurrentRevision, T1.HardwareKit_HardwareKitNumber, T1.HardwareKit_ExtraQuantityPercentage, T1.HardwareKit_CreatedBy, T1.HardwareKit_CreatedDate, T1.HardwareKit_ModifiedBy, T1.HardwareKit_ModifiedDate, T1.HardwareKit_IsDeleted)
    FROM (
        SELECT 
            T.HardwareKitId AS HardwareKit_HardwareKitId, 
            T.ProjectId AS HardwareKit_ProjectId, 
            T.Revision AS HardwareKit_Revision, 
            T.IsCurrentRevision AS HardwareKit_IsCurrentRevision, 
            T.HardwareKitNumber AS HardwareKit_HardwareKitNumber, 
            T.ExtraQuantityPercentage AS HardwareKit_ExtraQuantityPercentage, 
            T.CreatedBy AS HardwareKit_CreatedBy, 
            T.CreatedDate AS HardwareKit_CreatedDate, 
            T.ModifiedBy AS HardwareKit_ModifiedBy, 
            T.ModifiedDate AS HardwareKit_ModifiedDate, 
            T.IsDeleted AS HardwareKit_IsDeleted, 
            True AS _from0
        FROM WendtEquipmentTrackingDataAccessSQLModelStoreContainer.HardwareKit AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingEntities.HardwareKitEquipments.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView18()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing HardwareKitEquipments
        [WendtEquipmentTracking.DataAccess.SQL.Model.HardwareKitEquipment](T1.HardwareKitEquipment_HardwareKitEquipmentId, T1.HardwareKitEquipment_HardwareKitId, T1.HardwareKitEquipment_EquipmentId, T1.HardwareKitEquipment_QuantityToShip, T1.HardwareKitEquipment_IsDeleted)
    FROM (
        SELECT 
            T.HardwareKitEquipmentId AS HardwareKitEquipment_HardwareKitEquipmentId, 
            T.HardwareKitId AS HardwareKitEquipment_HardwareKitId, 
            T.EquipmentId AS HardwareKitEquipment_EquipmentId, 
            T.QuantityToShip AS HardwareKitEquipment_QuantityToShip, 
            T.IsDeleted AS HardwareKitEquipment_IsDeleted, 
            True AS _from0
        FROM WendtEquipmentTrackingDataAccessSQLModelStoreContainer.HardwareKitEquipment AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingEntities.Priorities.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView19()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Priorities
        [WendtEquipmentTracking.DataAccess.SQL.Model.Priority](T1.Priority_PriorityId, T1.Priority_ProjectId, T1.Priority_PriorityNumber, T1.Priority_DueDate, T1.Priority_EndDate, T1.Priority_ContractualShipDate, T1.Priority_EquipmentName, T1.Priority_CreatedBy, T1.Priority_CreatedDate, T1.Priority_ModifiedBy, T1.Priority_ModifiedDate, T1.Priority_IsDeleted)
    FROM (
        SELECT 
            T.PriorityId AS Priority_PriorityId, 
            T.ProjectId AS Priority_ProjectId, 
            T.PriorityNumber AS Priority_PriorityNumber, 
            T.DueDate AS Priority_DueDate, 
            T.EndDate AS Priority_EndDate, 
            T.ContractualShipDate AS Priority_ContractualShipDate, 
            T.EquipmentName AS Priority_EquipmentName, 
            T.CreatedBy AS Priority_CreatedBy, 
            T.CreatedDate AS Priority_CreatedDate, 
            T.ModifiedBy AS Priority_ModifiedBy, 
            T.ModifiedDate AS Priority_ModifiedDate, 
            T.IsDeleted AS Priority_IsDeleted, 
            True AS _from0
        FROM WendtEquipmentTrackingDataAccessSQLModelStoreContainer.Priority AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingEntities.Projects.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView20()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Projects
        [WendtEquipmentTracking.DataAccess.SQL.Model.Project](T1.Project_ProjectId, T1.Project_ProjectNumber, T1.Project_CreatedBy, T1.Project_CreatedDate, T1.Project_ModifiedBy, T1.Project_ModifiedDate, T1.Project_FreightTerms, T1.Project_ShipToCompany, T1.Project_ShipToAddress, T1.Project_ShipToCSZ, T1.Project_ShipToContact1, T1.Project_ShipToContact1PhoneFax, T1.Project_ShipToContact1Email, T1.Project_ShipToContact2, T1.Project_ShipToContact2PhoneFax, T1.Project_ShipToContact2Email, T1.Project_ShipToBroker, T1.Project_ShipToBrokerPhoneFax, T1.Project_ShipToBrokerEmail, T1.Project_PM, T1.Project_ReceivingHours, T1.Project_Notes, T1.Project_IsCustomsProject, T1.Project_IncludeSoftCosts, T1.Project_IsCompleted, T1.Project_IsDeleted)
    FROM (
        SELECT 
            T.ProjectId AS Project_ProjectId, 
            T.ProjectNumber AS Project_ProjectNumber, 
            T.CreatedBy AS Project_CreatedBy, 
            T.CreatedDate AS Project_CreatedDate, 
            T.ModifiedBy AS Project_ModifiedBy, 
            T.ModifiedDate AS Project_ModifiedDate, 
            T.FreightTerms AS Project_FreightTerms, 
            T.ShipToCompany AS Project_ShipToCompany, 
            T.ShipToAddress AS Project_ShipToAddress, 
            T.ShipToCSZ AS Project_ShipToCSZ, 
            T.ShipToContact1 AS Project_ShipToContact1, 
            T.ShipToContact1PhoneFax AS Project_ShipToContact1PhoneFax, 
            T.ShipToContact1Email AS Project_ShipToContact1Email, 
            T.ShipToContact2 AS Project_ShipToContact2, 
            T.ShipToContact2PhoneFax AS Project_ShipToContact2PhoneFax, 
            T.ShipToContact2Email AS Project_ShipToContact2Email, 
            T.ShipToBroker AS Project_ShipToBroker, 
            T.ShipToBrokerPhoneFax AS Project_ShipToBrokerPhoneFax, 
            T.ShipToBrokerEmail AS Project_ShipToBrokerEmail, 
            T.PM AS Project_PM, 
            T.ReceivingHours AS Project_ReceivingHours, 
            T.Notes AS Project_Notes, 
            T.IsCustomsProject AS Project_IsCustomsProject, 
            T.IncludeSoftCosts AS Project_IncludeSoftCosts, 
            T.IsCompleted AS Project_IsCompleted, 
            T.IsDeleted AS Project_IsDeleted, 
            True AS _from0
        FROM WendtEquipmentTrackingDataAccessSQLModelStoreContainer.Project AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingEntities.TruckingSchedules.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView21()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing TruckingSchedules
        [WendtEquipmentTracking.DataAccess.SQL.Model.TruckingSchedule](T1.TruckingSchedule_TruckingScheduleId, T1.TruckingSchedule_RequestDate, T1.TruckingSchedule_ProjectId, T1.TruckingSchedule_WorkOrder, T1.TruckingSchedule_PurchaseOrder, T1.TruckingSchedule_RequestedBy, T1.TruckingSchedule_ShipFromVendorId, T1.TruckingSchedule_ShipToVendorId, T1.TruckingSchedule_Description, T1.TruckingSchedule_NumPieces, T1.TruckingSchedule_Dimensions, T1.TruckingSchedule_Weight, T1.TruckingSchedule_Carrier, T1.TruckingSchedule_PickUpDate, T1.TruckingSchedule_Comments, T1.TruckingSchedule_Status, T1.TruckingSchedule_CreatedBy, T1.TruckingSchedule_CreatedDate, T1.TruckingSchedule_ModifiedBy, T1.TruckingSchedule_ModifiedDate, T1.TruckingSchedule_IsDeleted)
    FROM (
        SELECT 
            T.TruckingScheduleId AS TruckingSchedule_TruckingScheduleId, 
            T.RequestDate AS TruckingSchedule_RequestDate, 
            T.ProjectId AS TruckingSchedule_ProjectId, 
            T.WorkOrder AS TruckingSchedule_WorkOrder, 
            T.PurchaseOrder AS TruckingSchedule_PurchaseOrder, 
            T.RequestedBy AS TruckingSchedule_RequestedBy, 
            T.ShipFromVendorId AS TruckingSchedule_ShipFromVendorId, 
            T.ShipToVendorId AS TruckingSchedule_ShipToVendorId, 
            T.Description AS TruckingSchedule_Description, 
            T.NumPieces AS TruckingSchedule_NumPieces, 
            T.Dimensions AS TruckingSchedule_Dimensions, 
            T.Weight AS TruckingSchedule_Weight, 
            T.Carrier AS TruckingSchedule_Carrier, 
            T.PickUpDate AS TruckingSchedule_PickUpDate, 
            T.Comments AS TruckingSchedule_Comments, 
            T.Status AS TruckingSchedule_Status, 
            T.CreatedBy AS TruckingSchedule_CreatedBy, 
            T.CreatedDate AS TruckingSchedule_CreatedDate, 
            T.ModifiedBy AS TruckingSchedule_ModifiedBy, 
            T.ModifiedDate AS TruckingSchedule_ModifiedDate, 
            T.IsDeleted AS TruckingSchedule_IsDeleted, 
            True AS _from0
        FROM WendtEquipmentTrackingDataAccessSQLModelStoreContainer.TruckingSchedule AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingEntities.Vendors.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView22()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Vendors
        [WendtEquipmentTracking.DataAccess.SQL.Model.Vendor](T1.Vendor_VendorId, T1.Vendor_Name, T1.Vendor_Address, T1.Vendor_Contact1, T1.Vendor_PhoneFax, T1.Vendor_Email, T1.Vendor_CreatedBy, T1.Vendor_CreatedDate, T1.Vendor_ModifiedBy, T1.Vendor_ModifiedDate, T1.Vendor_IsDeleted)
    FROM (
        SELECT 
            T.VendorId AS Vendor_VendorId, 
            T.Name AS Vendor_Name, 
            T.Address AS Vendor_Address, 
            T.Contact1 AS Vendor_Contact1, 
            T.PhoneFax AS Vendor_PhoneFax, 
            T.Email AS Vendor_Email, 
            T.CreatedBy AS Vendor_CreatedBy, 
            T.CreatedDate AS Vendor_CreatedDate, 
            T.ModifiedBy AS Vendor_ModifiedBy, 
            T.ModifiedDate AS Vendor_ModifiedDate, 
            T.IsDeleted AS Vendor_IsDeleted, 
            True AS _from0
        FROM WendtEquipmentTrackingDataAccessSQLModelStoreContainer.Vendor AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingEntities.WorkOrderPrices.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView23()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing WorkOrderPrices
        [WendtEquipmentTracking.DataAccess.SQL.Model.WorkOrderPrice](T1.WorkOrderPrice_WorkOrderPriceId, T1.WorkOrderPrice_ProjectId, T1.WorkOrderPrice_WorkOrderNumber, T1.WorkOrderPrice_SalePrice, T1.WorkOrderPrice_CostPrice, T1.WorkOrderPrice_TotalWeight, T1.WorkOrderPrice_ReleasedPercent, T1.WorkOrderPrice_ShippedPercent, T1.WorkOrderPrice_CreatedBy, T1.WorkOrderPrice_CreatedDate, T1.WorkOrderPrice_ModifiedBy, T1.WorkOrderPrice_ModifiedDate, T1.WorkOrderPrice_IsDeleted)
    FROM (
        SELECT 
            T.WorkOrderPriceId AS WorkOrderPrice_WorkOrderPriceId, 
            T.ProjectId AS WorkOrderPrice_ProjectId, 
            T.WorkOrderNumber AS WorkOrderPrice_WorkOrderNumber, 
            T.SalePrice AS WorkOrderPrice_SalePrice, 
            T.CostPrice AS WorkOrderPrice_CostPrice, 
            T.TotalWeight AS WorkOrderPrice_TotalWeight, 
            T.ReleasedPercent AS WorkOrderPrice_ReleasedPercent, 
            T.ShippedPercent AS WorkOrderPrice_ShippedPercent, 
            T.CreatedBy AS WorkOrderPrice_CreatedBy, 
            T.CreatedDate AS WorkOrderPrice_CreatedDate, 
            T.ModifiedBy AS WorkOrderPrice_ModifiedBy, 
            T.ModifiedDate AS WorkOrderPrice_ModifiedDate, 
            T.IsDeleted AS WorkOrderPrice_IsDeleted, 
            True AS _from0
        FROM WendtEquipmentTrackingDataAccessSQLModelStoreContainer.WorkOrderPrice AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingDataAccessSQLModelStoreContainer.Broker.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView24()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Broker
        [WendtEquipmentTracking.DataAccess.SQL.Model.Store.Broker](T1.Broker_BrokerId, T1.Broker_Name, T1.Broker_Address, T1.Broker_Contact1, T1.Broker_PhoneFax, T1.Broker_Email, T1.Broker_CreatedBy, T1.Broker_CreatedDate, T1.Broker_ModifiedBy, T1.Broker_ModifiedDate, T1.Broker_IsDeleted)
    FROM (
        SELECT 
            T.BrokerId AS Broker_BrokerId, 
            T.Name AS Broker_Name, 
            T.Address AS Broker_Address, 
            T.Contact1 AS Broker_Contact1, 
            T.PhoneFax AS Broker_PhoneFax, 
            T.Email AS Broker_Email, 
            T.CreatedBy AS Broker_CreatedBy, 
            T.CreatedDate AS Broker_CreatedDate, 
            T.ModifiedBy AS Broker_ModifiedBy, 
            T.ModifiedDate AS Broker_ModifiedDate, 
            T.IsDeleted AS Broker_IsDeleted, 
            True AS _from0
        FROM WendtEquipmentTrackingEntities.Brokers AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingEntities.Brokers.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView25()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Brokers
        [WendtEquipmentTracking.DataAccess.SQL.Model.Broker](T1.Broker_BrokerId, T1.Broker_Name, T1.Broker_Address, T1.Broker_Contact1, T1.Broker_PhoneFax, T1.Broker_Email, T1.Broker_CreatedBy, T1.Broker_CreatedDate, T1.Broker_ModifiedBy, T1.Broker_ModifiedDate, T1.Broker_IsDeleted)
    FROM (
        SELECT 
            T.BrokerId AS Broker_BrokerId, 
            T.Name AS Broker_Name, 
            T.Address AS Broker_Address, 
            T.Contact1 AS Broker_Contact1, 
            T.PhoneFax AS Broker_PhoneFax, 
            T.Email AS Broker_Email, 
            T.CreatedBy AS Broker_CreatedBy, 
            T.CreatedDate AS Broker_CreatedDate, 
            T.ModifiedBy AS Broker_ModifiedBy, 
            T.ModifiedDate AS Broker_ModifiedDate, 
            T.IsDeleted AS Broker_IsDeleted, 
            True AS _from0
        FROM WendtEquipmentTrackingDataAccessSQLModelStoreContainer.Broker AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingDataAccessSQLModelStoreContainer.HardwareCommercialCode.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView26()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing HardwareCommercialCode
        [WendtEquipmentTracking.DataAccess.SQL.Model.Store.HardwareCommercialCode](T1.HardwareCommercialCode_HardwareCommercialCodeId, T1.HardwareCommercialCode_PartNumber, T1.HardwareCommercialCode_Description, T1.HardwareCommercialCode_CommodityCode, T1.HardwareCommercialCode_CreatedBy, T1.HardwareCommercialCode_CreatedDate, T1.HardwareCommercialCode_ModifiedBy, T1.HardwareCommercialCode_ModifiedDate, T1.HardwareCommercialCode_IsDeleted)
    FROM (
        SELECT 
            T.HardwareCommercialCodeId AS HardwareCommercialCode_HardwareCommercialCodeId, 
            T.PartNumber AS HardwareCommercialCode_PartNumber, 
            T.Description AS HardwareCommercialCode_Description, 
            T.CommodityCode AS HardwareCommercialCode_CommodityCode, 
            T.CreatedBy AS HardwareCommercialCode_CreatedBy, 
            T.CreatedDate AS HardwareCommercialCode_CreatedDate, 
            T.ModifiedBy AS HardwareCommercialCode_ModifiedBy, 
            T.ModifiedDate AS HardwareCommercialCode_ModifiedDate, 
            T.IsDeleted AS HardwareCommercialCode_IsDeleted, 
            True AS _from0
        FROM WendtEquipmentTrackingEntities.HardwareCommercialCodes AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingEntities.HardwareCommercialCodes.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView27()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing HardwareCommercialCodes
        [WendtEquipmentTracking.DataAccess.SQL.Model.HardwareCommercialCode](T1.HardwareCommercialCode_HardwareCommercialCodeId, T1.HardwareCommercialCode_PartNumber, T1.HardwareCommercialCode_Description, T1.HardwareCommercialCode_CommodityCode, T1.HardwareCommercialCode_CreatedBy, T1.HardwareCommercialCode_CreatedDate, T1.HardwareCommercialCode_ModifiedBy, T1.HardwareCommercialCode_ModifiedDate, T1.HardwareCommercialCode_IsDeleted)
    FROM (
        SELECT 
            T.HardwareCommercialCodeId AS HardwareCommercialCode_HardwareCommercialCodeId, 
            T.PartNumber AS HardwareCommercialCode_PartNumber, 
            T.Description AS HardwareCommercialCode_Description, 
            T.CommodityCode AS HardwareCommercialCode_CommodityCode, 
            T.CreatedBy AS HardwareCommercialCode_CreatedBy, 
            T.CreatedDate AS HardwareCommercialCode_CreatedDate, 
            T.ModifiedBy AS HardwareCommercialCode_ModifiedBy, 
            T.ModifiedDate AS HardwareCommercialCode_ModifiedDate, 
            T.IsDeleted AS HardwareCommercialCode_IsDeleted, 
            True AS _from0
        FROM WendtEquipmentTrackingDataAccessSQLModelStoreContainer.HardwareCommercialCode AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingDataAccessSQLModelStoreContainer.User.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView28()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing User
        [WendtEquipmentTracking.DataAccess.SQL.Model.Store.User](T1.User_UserId, T1.User_UserName, T1.User_ProjectId)
    FROM (
        SELECT 
            T.UserId AS User_UserId, 
            T.UserName AS User_UserName, 
            T.ProjectId AS User_ProjectId, 
            True AS _from0
        FROM WendtEquipmentTrackingEntities.Users AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WendtEquipmentTrackingEntities.Users.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView29()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Users
        [WendtEquipmentTracking.DataAccess.SQL.Model.User](T1.User_UserId, T1.User_UserName, T1.User_ProjectId)
    FROM (
        SELECT 
            T.UserId AS User_UserId, 
            T.UserName AS User_UserName, 
            T.ProjectId AS User_ProjectId, 
            True AS _from0
        FROM WendtEquipmentTrackingDataAccessSQLModelStoreContainer.User AS T
    ) AS T1");
        }
    }
}
